# Stage 1: Proses Build
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
# Membuat folder /build
RUN npm run build

# Stage 2: Proses Running
FROM node:20-alpine
WORKDIR /app
# Ambil hasil build dan dependensi dari stage builder
COPY --from=builder /app/build ./build
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/node_modules ./node_modules

# SvelteKit adapter-node menggunakan environment variable PORT
ENV PORT=5000
EXPOSE 5000

CMD ["node", "build"]